name: Docker Build and Push

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Extract Date and Time for Tag
      id: vars
      run: echo "IMAGE_TAG=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/your_image_name:latest .
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/your_image_name:latest ${{ secrets.DOCKERHUB_USERNAME }}/your_image_name:${{ env.IMAGE_TAG }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/your_image_name:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/your_image_name:${{ env.IMAGE_TAG }}
